### ISSUE TITLE
`ARDUINO_ARCH_RENESAS_UNO` is not defined

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platform-renesas-ra#11]
The original Arduino core defines `ARDUINO_ARCH_{build.arch}`, which leads to `ARDUINO_ARCH_RENESAS_UNO` being defined:

```cpp
-DARDUINO=10607 -DARDUINO_UNOWIFIR4 -DARDUINO_ARCH_RENESAS_UNO -DARDUINO_ARCH_RENESAS -DARDUINO_FSP -D_XOPEN_SOURCE
```

In PlatformIO, this definition is missing:

```cpp
-DPLATFORMIO=60110 -DARDUINO_UNOWIFIR4 -DARDUINO_UNOR4_WIFI -DNO_USB -DBACKTRACE_SUPPORT -DLWIP_DNS=1 -DCFG_TUSB_MCU=OPT_MCU_RAXXX -DNO_OTA_NETWORK -D_RA_CORE=CM4 -D_RENESAS_RA_ -DARDUINO=10810 -DARDUINO_ARCH_RENESAS -DARDUINO_FSP -D_XOPEN_SOURCE
```

This is already in use by some libraries and code examples: https://github.com/search?q=ARDUINO_ARCH_RENESAS_UNO&type=code

**Comment by valeros** [comment]
Thanks for reporting, fixed in the dev branch.
