### ISSUE TITLE
JLink Device Names wrong

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-renesas-ra#19]
Per <https://community.platformio.org/t/arduino-portenta-c33-jlink-flash-problem/37346>

https://github.com/platformio/platform-renesas-ra/blob/695525c9dcc175a6ef440f4866e5019f1d9cb575/boards/portenta_c33.json#L25-L29

device name should be `R7FA6M5BH` per https://www.segger.com/supported-devices/search/R7FA6M5

https://github.com/platformio/platform-renesas-ra/blob/695525c9dcc175a6ef440f4866e5019f1d9cb575/boards/uno_r4_minima.json#L29

https://github.com/platformio/platform-renesas-ra/blob/695525c9dcc175a6ef440f4866e5019f1d9cb575/boards/uno_r4_wifi.json#L35

should be `R7FA4M1AB` per https://www.segger.com/supported-devices/search/RA4M1

**Comment by valeros** [comment]
Many thanks, updated!
