### ISSUE TITLE
Please upgrade the Arduino framework

### ISSUE THREAD

**Issue by pisto** [platformio/platform-renesas-ra#25]
I am not familiar with the ownership of platformio packages, so I'm sorry in advance if this is not the correct repo for the issue.

I noticed that this platform has an outdated version of the Arduino framework. Basically I'm asking to bump the linked versions like in #22 to version 1.2.2, and hopefully to have a clear documentation on the process of getting dependent library updates into platformio.

Before bumping versions in [here](https://github.com/platformio/platform-renesas-ra/blob/develop/platform.json#L49) and [here](https://github.com/platformio/platform-renesas-ra/blob/develop/platform.json#L55), the relevant framework packages need to be updated to the latest version in the platformio registry, but I have been unable so far to reach who can do that. The framework packages are [platformio/framework-arduinorenesas-portenta](https://registry.platformio.org/tools/platformio/framework-arduinorenesas-portenta/versions) and [platformio/framework-arduinorenesas-uno](https://registry.platformio.org/tools/platformio/framework-arduinorenesas-uno/versions), both built from this [Arduino repo](https://github.com/arduino/ArduinoCore-renesas).

I opened an [issue](https://github.com/arduino/ArduinoCore-renesas/issues/380) for the Arduino team because the author of the packages in the registry is listed as Arduino, but apparently they don't pushy the library themselves.

When the framework packages are updated, I will open a merge request with the changes in the platform json.

**Comment by reganissu** [comment]
following this
