### ISSUE TITLE
Intellisense issue on some systems

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-renesas-ra#5]
Per https://github.com/maxgerhardt/platform-renesas/issues/1#issuecomment-1625310655.

Magically on this user's system, the `c_cpp_properties.json` gets wrongly generated with missing path seperator character:
On my old platform:

![grafik](https://github.com/platformio/platform-renesas-ra/assets/26485477/dcc190f4-a5be-4b5a-ad69-87ff27bddf69)

On this current-version version platform:
```json
 "compilerArgs": [ "-mcpu=cortex-m4", "-mfloat-abi=hard", "-mfpu=fpv4-sp-d16", "-mthumb", "-iprefixC:Users94837.platformiopackagesframework-arduinorenesas-uno", "@C:Users94837.platformiopackagesframework-arduinorenesas-unovariantsUNOWIFIR4includes.txt", "" ]
```

I have no idea how that's possible since it does work on my Windows 10, x64, system:

```json
            "compilerPath": "C:/Users/Max/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe",
            "compilerArgs": [
                "-mcpu=cortex-m4",
                "-mfloat-abi=hard",
                "-mfpu=fpv4-sp-d16",
                "-mthumb",
                "-iprefixC:/Users/Max/.platformio/packages/framework-arduinorenesas-uno",
                "@C:/Users/Max/.platformio/packages/framework-arduinorenesas-uno/variants/UNOWIFIR4/includes.txt",
                ""
            ]
```

I pushed a countermeasure for this, that is, in the `__idedata` phase, don't return `-iprefix <prefx> @<file>`, but actually expand out all include paths:  https://github.com/maxgerhardt/platform-renesas/blob/bc8d2f1ae4d0a8507dbee06861a884293c0d83a2/builder/frameworks/arduino/mbed-core/arduino-core-mbed.py#L157-L179

According to the user, the problem remained present even after reinstalling everything and trying it on a different computer. Might be issues with specific character encoding sets, e.g. Chinese? I have no idea real idea though. They had the exact same VSCode version, C/C++ extension version, PlatformIO core and PlatformIO extension version as me.

**Comment by maxgerhardt** [comment]
@LYB030 can you again retry with [PlatformIO CLI](https://github.com/Community-PIO-CH32V/ch32-pio-projects#update-via-platformio-core-cli) -> 
```
pio pkg update -g -p renesas-ra
```
and Ctrl+Shift+P -> Rebuild Intellisense.

Is the Intellisense issue still there?

**Comment by LYB030** [comment]
Bug solved, thank you for your help！
